# Generated by Django 5.2.5 on 2025-09-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("mood", models.CharField(blank=True, max_length=64)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("classical", "Classical"),
                            ("jazz", "Jazz"),
                            ("pop", "Pop"),
                            ("rock", "Rock"),
                            ("ambient", "Ambient"),
                            ("electronic", "Electronic"),
                        ],
                        default="ambient",
                        max_length=32,
                    ),
                ),
                (
                    "instruments",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated instruments",
                        max_length=255,
                    ),
                ),
                ("tempo_bpm", models.PositiveIntegerField(default=120)),
                ("length_seconds", models.PositiveIntegerField(default=30)),
                (
                    "model_used",
                    models.CharField(default="stub-generator", max_length=255),
                ),
                ("audio_file", models.FileField(upload_to="compositions/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
